# Generated by Django 4.2.7 on 2023-12-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0003_alter_department_name_alter_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='project_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
