# Generated by Django 4.2.7 on 2023-12-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0004_employee_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empskills',
            name='employee',
        ),
        migrations.AddField(
            model_name='empskills',
            name='emp_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
